### ISSUE TITLE
Add support for Artifactory 5.4

### ISSUE THREAD

**Issue by jbrockopp** [lusis/go-artifactory#13]
Release notes [here](https://www.jfrog.com/confluence/display/RTF/Release+Notes#ReleaseNotes-Artifactory5.4)

**Comment by jbrockopp** [comment]
@lusis are you open to me submitting a PR for this? I'm not sure if you are looking for someone to be helping you out with this code base or not.. just lmk.

**Comment by lusis** [comment]
Oh yes please do. We've not upgraded just yet so I haven't been needing to add it just yet. Are you mainly needing updated auth bits?

**Comment by jbrockopp** [comment]
@lusis this is accomplished with [#14](https://github.com/lusis/go-artifactory/pull/14)
